coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 5%
        if_ci_failed: error
    patch:
      default:
        target: 80%
        threshold: 5%
        if_ci_failed: error
ignore:
  - "cmd"
  - "examples"
  - "**/*.pb.go"
  - "**/zz_generated.*.go"
  # This is the test library.
  - "tests/internal/envtest.go"
